from pydantic import BaseModel, Field
from core.planning.task_plan import TaskPlan
from langchain_core.messages import HumanMessage, SystemMessage


class PlannedStep(BaseModel):
    """Represents one step generated by the planner."""

    description: str = Field(
        description="A clear and actionable task step."
    )


class PlannerOutput(BaseModel):
    """Structured output returned by the task planner."""

    goal: str = Field(
        description="The main goal of the user's request."
    )

    steps: list[PlannedStep] = Field(
        description="Ordered steps required to complete the goal."
    )


class TaskPlanner:
    """Creates structured task plans from user requests."""

    def __init__(self, llm):

        # Keep the original language model
        self.llm = llm

        # Force the model to return PlannerOutput
        self.structured_llm = llm.with_structured_output(PlannerOutput)


        # Tell the planner how to create good task steps
        self.system_prompt = """
You are the task planner for Jarvis.

Your job is to turn the user's request into a clear and ordered task plan.

Rules:
- Keep the goal close to the user's original request.
- Create only the steps needed to complete the task.
- Make each step clear and actionable.
- Keep steps at a high level.
- Do not generate Python code.
- Do not generate mouse coordinates.
- Do not generate keyboard shortcuts unless they are part of the user's request.
- Each step should describe one clear objective, not low-level implementation details.
- Do not invent tools, files, websites, or information.
- Do not mark any step as completed.
- Do not execute the task.
- Do not add unnecessary confirmation steps.
- Put verification into the plan only when it is useful.
- Preserve important user constraints.
- Preserve the user's language for the goal and steps when possible.
- Do not invent missing criteria or details that the user did not specify.
"""


    async def plan(self, user_request: str) -> TaskPlan:
        user_request = user_request.strip()

        if not user_request:
            raise ValueError("User request cannot be empty.")

        # Build the messages for the planner
        messages = [
            SystemMessage(content=self.system_prompt),
            HumanMessage(content=user_request),
        ]

        # Ask the model to create a structured plan
        output: PlannerOutput = await self.structured_llm.ainvoke(messages)

        task_plan = TaskPlan(
            goal=output.goal.strip()
        )

        for planned_step in output.steps:
            description = planned_step.description.strip()

            if description:
                task_plan.add_step(description)


        # A valid task must contain at least one step
        if not task_plan.steps:
            raise ValueError("Planner returned no usable steps.")

        return task_plan